{
  "comments": [
    {
      "key": {
        "uuid": "f5e62cbb_fcd792ec",
        "filename": "ethernet_interface.cpp",
        "patchSetId": 28
      },
      "lineNbr": 805,
      "author": {
        "id": 1000022
      },
      "writtenOn": "2019-10-14T17:53:32Z",
      "side": 1,
      "message": "why this condition is required?",
      "range": {
        "startLine": 804,
        "startChar": 2,
        "endLine": 805,
        "endChar": 5
      },
      "revId": "5c1a6181d537800047592e52bc731badda98c388",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "b162f0d5_6f5dd54d",
        "filename": "ethernet_interface.cpp",
        "patchSetId": 28
      },
      "lineNbr": 805,
      "author": {
        "id": 1000350
      },
      "writtenOn": "2019-10-15T06:18:32Z",
      "side": 1,
      "message": "i thought of setting Maxattempts only if fallback is configured.\nby default maxattempts value is infinity and it keeps trying to discover dhcp server\nso its better to assign a value.\nremove this check",
      "parentUuid": "f5e62cbb_fcd792ec",
      "range": {
        "startLine": 804,
        "startChar": 2,
        "endLine": 805,
        "endChar": 5
      },
      "revId": "5c1a6181d537800047592e52bc731badda98c388",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}